# Generated by Django 5.0.4 on 2024-04-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(to='command.course'),
        ),
    ]
