# Generated by Django 5.0.4 on 2024-04-30 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0004_alter_course_prerequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.TextField(choices=[(1, '09:00 - 10:30'), (2, '10:45 - 12:15'), (3, '12:30 - 02:00'), (4, '02:15 - 03:45')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command.room')),
            ],
        ),
    ]
