# Generated by Django 5.0.4 on 2024-04-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0005_room_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.TextField(choices=[(1, 'Sun'), (2, 'Mon'), (3, 'Tue'), (4, 'Wed'), (5, 'Thu')], default=1),
            preserve_default=False,
        ),
    ]
