# Generated by Django 5.0.4 on 2024-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0006_timeslot_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='minimum_level',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
