@startuml

skinparam linetype ortho

Entity Userinfo {
    id: int <<pk>>
    username: varchar UNIQUE
    first_name: varchar
    last_name: varchar
    date_of_birth: datetime
    gender: enum {'M', 'F'}
    password: varchar
}

Entity Student {
    student_id: int <<pk>> <<fk>>
    major_id: int
    cgpa: float
    level: int
    enrolled: boolean
}

Entity Instructor {
    instructor_id: int <<pk>> <<fk>>
}

Entity Ticket {
    ticket_id: int <<pk>> <<fk>>
    user_id: int <<fk>>
    ticket_content: varchar
}

Entity Semester {
    semester_id: int <<pk>>
    semester_type: enum {Summer, Fall, Spring}
    semester_year: varchar
}

Entity Enrollment {
    student_id: int <<pk>> <<fk>>
    course_id: int <<pk>> <<fk>>
    semester_id: int <<pk>> <<fk>>
    instructor_id: int <<pk>> <<fk>>
    classwork_marks: int
    homework_marks: int
    midterm_mark: int
    final_mark: int
    withdraw: enum {'W', 'F'}
    gpa: varchar
}

Entity AbsenceInstance {
    enrollment_id: int <<fk>>
    date: datetime
}

Entity Faculty {
    faculty_id: int <<pk>>
    faculty_name: varchar
}

Entity Major {
    major_id: int <<pk>>
    major_name: varchar
    degree: varchar
    faculty_id: int NOT NULL <<fk>

}

Entity Timeslot {
    time_slot_id: int <<pk>>
    room_id: int <<pk>> <<fk>>
    course_id: int <<fk>>

}

Entity Room {
    room_id: int <<pk>>
    room_name: varchar

}

Entity Course {
    course_id: int <<pk>>
    course_title: varchar
    course_description: varchar
    credit_hours: int
    mandatory: boolean
    faculty_id: int <<fk>>
    minimum_level: int

}

Userinfo ||--|| Instructor
Userinfo ||--|| Student
Userinfo ||--o{ Ticket
Major ||--o{ Student
Major ||--|| Faculty
Enrollment }o---o{ Instructor
Enrollment }o---|| Student
Enrollment }o---|| Course
Enrollment }o---|| Semester
Enrollment ||---o{ AbsenceInstance
Course }o---|| Faculty
Timeslot }o---|| Room
Timeslot }o---|| Course

Course }o---o{ Course: requires

@enduml
